controller_list:
  - name: ""
    action_ns: blue/vel_based_pos_traj_controller/follow_joint_trajectory
    type: FollowJointTrajectory
    joints:
      - blue_shoulder_pan_joint
      - blue_shoulder_lift_joint
      - blue_elbow_joint
      - blue_wrist_1_joint
      - blue_wrist_2_joint
      - blue_wrist_3_joint

