red_arm:
  # Settings for ros_control control loop
  hardware_control_loop:
     loop_hz: 125

  # Settings for ros_control hardware interface
  hardware_interface:
     joints:
       - red_shoulder_pan_joint
       - red_shoulder_lift_joint
       - red_elbow_joint
       - red_wrist_1_joint
       - red_wrist_2_joint
       - red_wrist_3_joint
  
  # Publish all joint states ----------------------------------
  joint_state_controller:
     type:         joint_state_controller/JointStateController
     publish_rate: 125
  
  # Publish wrench ----------------------------------
  force_torque_sensor_controller:
     type:         force_torque_sensor_controller/ForceTorqueSensorController
     publish_rate: 125
  
  # Joint Trajectory Controller - position based -------------------------------
  # For detailed explanations of parameter see http://wiki.ros.org/joint_trajectory_controller
  
  controller_list:
     - name: /pos_based_pos_traj_controller
       action_ns: position_controllers
       type: JointTrajectoryController
       default: true
       joints:
         - red_shoulder_pan_joint
         - red_shoulder_lift_joint
         - red_elbow_joint
         - red_wrist_1_joint
         - red_wrist_2_joint
         - red_wrist_3_joint
       constraints:
          goal_time: 0.6
          stopped_velocity_tolerance: 0.05
          red_shoulder_pan_joint: {trajectory: 0.1, goal: 0.1}
          red_shoulder_lift_joint: {trajectory: 0.1, goal: 0.1}
          red_elbow_joint: {trajectory: 0.1, goal: 0.1}
          red_wrist_1_joint: {trajectory: 0.1, goal: 0.1}
          red_wrist_2_joint: {trajectory: 0.1, goal: 0.1}
          red_wrist_3_joint: {trajectory: 0.1, goal: 0.1}
       stop_trajectory_duration: 0.5
       state_publish_rate:  125
       action_monitor_rate: 10
       # state_publish_rate:  50 # Defaults to 50
       # action_monitor_rate: 20 # Defaults to 20
       #stop_trajectory_duration: 0 # Defaults to 0.0
       # Joint Trajectory Controller -------------------------------
    # For detailed explanations of parameter see http://wiki.ros.org/joint_trajectory_controller
     - name: /vel_based_pos_traj_controller
       action_ns: velocity_controllers
       type: JointTrajectoryController
       default: true
       joints:
         - red_shoulder_pan_joint
         - red_shoulder_lift_joint
         - red_elbow_joint
         - red_wrist_1_joint
         - red_wrist_2_joint
         - red_wrist_3_joint
       constraints:
          goal_time: 0.6
          stopped_velocity_tolerance: 0.05
          red_shoulder_pan_joint: {trajectory: 0.1, goal: 0.1}
          red_shoulder_lift_joint: {trajectory: 0.1, goal: 0.1}
          red_elbow_joint: {trajectory: 0.1, goal: 0.1}
          red_wrist_1_joint: {trajectory: 0.1, goal: 0.1}
          red_wrist_2_joint: {trajectory: 0.1, goal: 0.1}
          red_wrist_3_joint: {trajectory: 0.1, goal: 0.1}
       stop_trajectory_duration: 0.5
       state_publish_rate:  125
       action_monitor_rate: 10
       gains:
       #These values have not been optimized
          red_shoulder_pan_joint:  {p: 5.0,  i: 0.05, d: 0.1, i_clamp: 1}
          red_shoulder_lift_joint: {p: 5.0,  i: 0.05, d: 0.1, i_clamp: 1}
          red_elbow_joint:         {p: 5.0,  i: 0.05, d: 0.1, i_clamp: 1}
          red_wrist_1_joint:       {p: 5.0,  i: 0.05, d: 0.1, i_clamp: 1}
          red_wrist_2_joint:       {p: 5.0,  i: 0.05, d: 0.1, i_clamp: 1}
          red_wrist_3_joint:       {p: 5.0,  i: 0.05, d: 0.1, i_clamp: 1}
       # Use a feedforward term to reduce the size of PID gains
       velocity_ff:
          red_shoulder_pan_joint: 1.0
          red_shoulder_lift_joint: 1.0
          red_elbow_joint: 1.0
          red_wrist_1_joint: 1.0
          red_wrist_2_joint: 1.0
          red_wrist_3_joint: 1.0
          
     - name: /joint_group_vel_controller
       action_ns: velocity_controllers
       type: JointGroupVelocityController
       default: true
       joints:
         - red_shoulder_pan_joint
         - red_shoulder_lift_joint
         - red_elbow_joint
         - red_wrist_1_joint
         - red_wrist_2_joint
         - red_wrist_3_joint