controller_list:
  - name: "blue"
    action_ns: vel_based_pos_traj_controller/follow_joint_trajectory
    type: FollowJointTrajectory
    joints:
      - blue_shoulder_pan_joint
      - blue_shoulder_lift_joint
      - blue_elbow_joint
      - blue_wrist_1_joint
      - blue_wrist_2_joint
      - blue_wrist_3_joint
  - name: "red"
    action_ns: vel_based_pos_traj_controller/follow_joint_trajectory
    type: FollowJointTrajectory
    joints:
      - red_shoulder_pan_joint
      - red_shoulder_lift_joint
      - red_elbow_joint
      - red_wrist_1_joint
      - red_wrist_2_joint
      - red_wrist_3_joint
