controller_list:
  - name: fake_blue_arm_controller
    joints:
      - blue_shoulder_pan_joint
      - blue_shoulder_lift_joint
      - blue_elbow_joint
      - blue_wrist_1_joint
      - blue_wrist_2_joint
      - blue_wrist_3_joint
  - name: fake_red_arm_controller
    joints:
      - red_shoulder_pan_joint
      - red_shoulder_lift_joint
      - red_elbow_joint
      - red_wrist_1_joint
      - red_wrist_2_joint
      - red_wrist_3_joint
  - name: fake_blue_gripper_controller
    joints:
      - gripper_finger1_joint
  - name: fake_red_gripper_controller
    joints:
      - palm_finger_1_joint
      - finger_1_joint_1
      - finger_1_joint_2
      - finger_1_joint_3
      - palm_finger_2_joint
      - finger_2_joint_1
      - finger_2_joint_2
      - finger_2_joint_3
      - finger_middle_joint_1
      - finger_middle_joint_2
      - finger_middle_joint_3
  - name: fake_dual_controller
    joints:
      - blue_shoulder_pan_joint
      - blue_shoulder_lift_joint
      - blue_elbow_joint
      - blue_wrist_1_joint
      - blue_wrist_2_joint
      - blue_wrist_3_joint
      - red_shoulder_pan_joint
      - red_shoulder_lift_joint
      - red_elbow_joint
      - red_wrist_1_joint
      - red_wrist_2_joint
      - red_wrist_3_joint