dual:
  # Publish all joint states ----------------------------------
  joint_state_controller:
     type:         joint_state_controller/JointStateController
     publish_rate: 125
  # Joint Trajectory Controller - position based -------------------------------
  # For detailed explanations of parameter see http://wiki.ros.org/joint_trajectory_controller
  
  blue_arm_controller:
     type: position_controllers/JointTrajectoryController
     joints:
       - blue_shoulder_pan_joint
       - blue_shoulder_lift_joint
       - blue_elbow_joint
       - blue_wrist_1_joint
       - blue_wrist_2_joint
       - blue_wrist_3_joint
     #constraints:
     #   goal_time: 20.0
     #   stopped_velocity_tolerance: 0.05
     #   blue_shoulder_pan_joint: {trajectory: 0.9, goal: 0.9}
     #   blue_shoulder_lift_joint: {trajectory: 0.9, goal: 0.9}
     #   blue_elbow_joint: {trajectory: 0.9, goal: 0.9}
     #   blue_wrist_1_joint: {trajectory: 0.9, goal: 0.9}
     #   blue_wrist_2_joint: {trajectory: 0.9, goal: 0.9}
     #   blue_wrist_3_joint: {trajectory: 0.9, goal: 0.9}  uncomment the 'contraints' section
     #gains:
        #These values have not been optimized!!
        #blue_shoulder_pan_joint:  {p: 0,  i: 0, d: 0, i_clamp: 0}
        #blue_shoulder_lift_joint: {p: 0,  i: 0, d: 0, i_clamp: 0}
        #blue_elbow_joint:         {p: 0,  i: 0, d: 0, i_clamp: 0}
        #blue_wrist_1_joint:       {p: 0,  i: 0, d: 0, i_clamp: 0}
        #blue_wrist_2_joint:       {p: 0,  i: 0, d: 0, i_clamp: 0}
        #blue_wrist_3_joint:       {p: 0,  i: 0, d: 0, i_clamp: 0}

  red_arm_controller:
     type: position_controllers/JointTrajectoryController
     joints:
       - red_shoulder_pan_joint
       - red_shoulder_lift_joint
       - red_elbow_joint
       - red_wrist_1_joint
       - red_wrist_2_joint
       - red_wrist_3_joint
     constraints:
        goal_time: 0.6
        stopped_velocity_tolerance: 0.05
        red_shoulder_pan_joint: {trajectory: 0.1, goal: 0.1}
        red_shoulder_lift_joint: {trajectory: 0.1, goal: 0.1}
        red_elbow_joint: {trajectory: 0.1, goal: 0.1}
        red_wrist_1_joint: {trajectory: 0.1, goal: 0.1}
        red_wrist_2_joint: {trajectory: 0.1, goal: 0.1}
        red_wrist_3_joint: {trajectory: 0.1, goal: 0.1}
     #gains:
        #These values have not been optimized!!
        #red_shoulder_pan_joint:  {p: 5.0,  i: 0.05, d: 0.1, i_clamp: 1}
        #red_shoulder_lift_joint: {p: 5.0,  i: 0.05, d: 0.1, i_clamp: 1}
        #red_elbow_joint:         {p: 5.0,  i: 0.05, d: 0.1, i_clamp: 1}
        #red_wrist_1_joint:       {p: 5.0,  i: 0.05, d: 0.1, i_clamp: 1}
        #red_wrist_2_joint:       {p: 5.0,  i: 0.05, d: 0.1, i_clamp: 1}
        #red_wrist_3_joint:       {p: 5.0,  i: 0.05, d: 0.1, i_clamp: 1}

  blue_gripper_controller:
     type: position_controllers/JointTrajectoryController
     joints:
       - gripper_finger1_joint

  red_gripper_controller:
     type: position_controllers/JointTrajectoryController
     joints:
       - palm_finger_1_joint
       - finger_1_joint_1
       - finger_1_joint_2
       - finger_1_joint_3
       - palm_finger_2_joint
       - finger_2_joint_1
       - finger_2_joint_2
       - finger_2_joint_3
       - finger_middle_joint_1
       - finger_middle_joint_2
       - finger_middle_joint_3
