controller_manager_ns: 'controller_manager'
controller_list:
  - name: dual/blue_arm_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - blue_shoulder_pan_joint
      - blue_shoulder_lift_joint
      - blue_elbow_joint
      - blue_wrist_1_joint
      - blue_wrist_2_joint
      - blue_wrist_3_joint
  - name: dual/red_arm_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - red_shoulder_pan_joint
      - red_shoulder_lift_joint
      - red_elbow_joint
      - red_wrist_1_joint
      - red_wrist_2_joint
      - red_wrist_3_joint
  - name: dual/blue_gripper_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - gripper_finger1_joint
  - name: dual/red_gripper_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - palm_finger_1_joint
      - finger_1_joint_1
      - finger_1_joint_2
      - finger_1_joint_3
      - palm_finger_2_joint
      - finger_2_joint_1
      - finger_2_joint_2
      - finger_2_joint_3
      - finger_middle_joint_1
      - finger_middle_joint_2
      - finger_middle_joint_3
  #add the "gripper controllers" from the github repo - carefully read then add

  #- name: dual_controller
  #  action_ns: follow_joint_trajectory
  #  default: True
  #  type: FollowJointTrajectory
  #  joints:
  #    - blue_shoulder_pan_joint
  #    - blue_shoulder_lift_joint
  #    - blue_elbow_joint
  #    - blue_wrist_1_joint
  #    - blue_wrist_2_joint
  #    - blue_wrist_3_joint
  #    - red_shoulder_pan_joint
  #    - red_shoulder_lift_joint
  #    - red_elbow_joint
  #    - red_wrist_1_joint
  #    - red_wrist_2_joint
  #    - red_wrist_3_joint
